Repository Speewack/wlts-import, pull requests merged in 2018-05, with the labels that each got.

#6 Improved error reporting and added ability to export .kml map of ward members
  .gitignore
  README.md
  pom.xml
  src/main/java/org/randywebb/wlts/Main.java
  src/main/java/org/randywebb/wlts/beans/AbstractBean.java
  src/main/java/org/randywebb/wlts/beans/Address.java
  src/main/java/org/randywebb/wlts/beans/Assignment.java
  src/main/java/org/randywebb/wlts/beans/Companionship.java
  src/main/java/org/randywebb/wlts/beans/DetailedMember.java
  src/main/java/org/randywebb/wlts/beans/DetailedMinistered.java
  src/main/java/org/randywebb/wlts/beans/District.java
  src/main/java/org/randywebb/wlts/beans/Household.java
  src/main/java/org/randywebb/wlts/beans/HouseholdMember.java
  src/main/java/org/randywebb/wlts/beans/Teacher.java
  src/main/java/org/randywebb/wlts/beans/Visit.java
  src/main/java/org/randywebb/wlts/ldstools/json/AbstractConsumer.java
  src/main/java/org/randywebb/wlts/ldstools/json/DetailedMemberConsumer.java
  src/main/java/org/randywebb/wlts/ldstools/json/HouseholdConsumer.java
  src/main/java/org/randywebb/wlts/ldstools/json/HouseholdMemberConsumer.java
  src/main/java/org/randywebb/wlts/ldstools/rest/ApiCatalog.java
  src/main/java/org/randywebb/wlts/ldstools/rest/LdsToolsClient.java
  src/main/java/org/randywebb/wlts/ldstools/rest/MinistryHelpers.java
  src/main/java/org/randywebb/wlts/reports/DetailedMemberListCSV.java
  src/main/java/org/randywebb/wlts/reports/DetailedMinisteredCSV.java
  src/main/java/org/randywebb/wlts/reports/MinisteringKML.java
  src/main/java/org/randywebb/wlts/util/CSVWriter.java
  src/main/java/org/randywebb/wlts/util/KMLWriter.java
  src/main/java/org/randywebb/wlts/util/http/JSONResponseHandler.java
  src/main/resources/config.properties
Labels: bug, enhancement

#13 Add Toolchains
  pom.xml
Labels: enhancement

#11 Adding code analysis tools
  README.md
  pom.xml
  src/main/java/org/randywebb/wlts/Main.java
  src/main/java/org/randywebb/wlts/beans/AbstractBean.java
  src/main/java/org/randywebb/wlts/beans/Address.java
  src/main/java/org/randywebb/wlts/beans/Assignment.java
  src/main/java/org/randywebb/wlts/beans/Companionship.java
  src/main/java/org/randywebb/wlts/beans/DetailedMember.java
  src/main/java/org/randywebb/wlts/beans/DetailedMinistered.java
  src/main/java/org/randywebb/wlts/beans/District.java
  src/main/java/org/randywebb/wlts/beans/Household.java
  src/main/java/org/randywebb/wlts/beans/HouseholdMember.java
  src/main/java/org/randywebb/wlts/beans/Teacher.java
  src/main/java/org/randywebb/wlts/beans/Visit.java
  src/main/java/org/randywebb/wlts/beans/package-info.java
  src/main/java/org/randywebb/wlts/ldstools/rest/ApiCatalog.java
  src/main/java/org/randywebb/wlts/ldstools/rest/LdsToolsClient.java
  src/main/java/org/randywebb/wlts/ldstools/rest/MinistryHelpers.java
  src/main/java/org/randywebb/wlts/ldstools/rest/package-info.java
  src/main/java/org/randywebb/wlts/reports/DetailedMemberListCSV.java
  src/main/java/org/randywebb/wlts/reports/DetailedMinisteredCSV.java
  src/main/java/org/randywebb/wlts/reports/MinisteringKML.java
  src/main/java/org/randywebb/wlts/reports/package-info.java
  src/main/java/org/randywebb/wlts/util/AppConfig.java
  src/main/java/org/randywebb/wlts/util/KMLWriter.java
  src/main/java/org/randywebb/wlts/util/http/JSONResponseHandler.java
  src/main/java/org/randywebb/wlts/util/http/NoOpResponseHandler.java
  src/main/javadoc/overview.html
  src/main/resources/checkstyle.xml
  src/main/resources/config.properties
  src/main/resources/pmd.xml
Labels: enhancement

#19 Fixing hardcoded unit number in app properties
  src/main/java/org/randywebb/wlts/ldstools/rest/MinistryHelpers.java
  src/main/java/org/randywebb/wlts/reports/DetailedMinisteredCSV.java
  src/main/java/org/randywebb/wlts/reports/MinisteringKML.java
  src/main/resources/config.properties
Labels: bug
